### ISSUE TITLE
Sensitive Information Left behind

### ISSUE THREAD

**Issue by rvalle** [naturalis/ansible-opnsense#12]
The OPNSense configuration file may contain sensitive information, such as certificate private keys etc.

This ansible role modifies the configuration file in a temporal folder and the config file is left behind afterwards.

The file should be safely removed (overridden by ramdom data) after the role finishes execution. Perhaps by implementing some kind of securerm, saferm or similar task.

**Comment by rudibroekhuizen** [comment]
Thank you, merged
