### ISSUE TITLE
No root privileges needed for XML edit on localhost 

### ISSUE THREAD

**Issue by krauthosting** [naturalis/ansible-opnsense#34]
Hey folks from beloved NL,
thanks so far for your lean way of dealing with OPNsense via XML :love_you_gesture: 
Needed a change to roll as we don't run the Ansible controller as root.
Should be non breaking change to move become for play to task level.
Hope to contribute more in the future if you're willing to review & merge ...

**Comment by rvalle** [comment]
now that we look into privileges, to me the worst is that the XML seems to be available for all to read in the tmp folder, while it is being edited. that should also be an easy fix.

**Comment by zerwes** [comment]
I've created a PR #33 in order to make the path configurable.
We fetch the cfg befor and after each ansible run and commit the changes. Therefore we use:
```ft=yml
backup_filename: config-{{ inventory_hostname }}.xml
local_config_path: backup/{{ backup_filename }}
```
