### ISSUE TITLE
Manual vs Ansible Router Configuration

### ISSUE THREAD

**Issue by rvalle** [naturalis/ansible-opnsense#39]
Hi!

Right now, this ansible role will start by downloading the configuration, then apply changes and then upload the configuration.

What happens if routers have also been configured by hand?

How can we be certain that there are not critical configurations that have not been placed by the network administrator and are not in the playbooks?

I propose an alternative router configuration method (at least optional) where instead of starting by downloading the current router configuration, a "default" template (the configuration installed by default by opnsense) is used.

That way, manual configurations to the router would be wiped each time the playbooks are run, and the administrator knows that the unique source of truth is the ansible project.

This would require that ALL configurations are performed by ansible (which is not a bad thing).

I propose that this be made optional via a host variable, that would essentially change the source of initial configuration. something like:

```
# Setting the following to true will apply your playbook to
# the factory default configuration of the router istead of
# the current configuration, erasing any manual change made via GUI

opn_start_by_factory_default_configuration: true
```

This would also allow to rename certain configuration objects that now result in the creation of new ones, for example, in firewall rules the description is used as key, etc..

**Comment by zerwes** [comment]
Hello Rafael.
Currently this can be done using the following var:
```ft=yaml
opn_unset:
  - interfaces
  - dhcpd
  - filter
  - OPNsense/Firewall/Alias
  - gateways
  - vlans
  - staticroutes
  - laggs
```
This way you can even have a fine-grained control about what you want to rebuild from scratch: interfaces, aliases, firewall rules aka. filter etc.
Hope this helps.
Greetings
Klaus

**Comment by rvalle** [comment]
@zerwes I tried uset today, and the openvpn interface is gone.

I can not make it come back, not even deleting and re-creating my VPNs. Most Management we do is remote and the Firewall rules where on that interface.

Any idea how to get it back?

Is there any other drawback with unset: for example will it remove automatic firewall rules?

**Comment by rvalle** [comment]
Looks like in order to unset interfaces OpenVPN interface must be explicitly created with:

```
  - interface: openvpn
    settings:
      - key: if
        value: openvpn
      - key: internal_dynamic
        value: 1
      - key: virtual
        value: 1
      - key: type
        value: group
      - key: descr
        value: OpenVPN
```

**Comment by zerwes** [comment]
Hello Rafael.
I never tested this w/ openvpn
unset in fact just erases the complete subtree in xml and then it can be filled up again from scratch ....

**Comment by rvalle** [comment]
@zerwes that is why this functionality is good, forces you to know where each configuration comes from.

the openvpn interface is created by the VPN functionality, but I really don't know when. because deleting and creating the VPN again did not make it reapear. 

Anyway, there is the workaround.
