### ISSUE TITLE
Broken Alias in new Module

### ISSUE THREAD

**Issue by rvalle** [naturalis/ansible-opnsense#9]
OPN Sense includes now a module of Firewall aliases that is new and compatible with the REST API.

The generated XML is different, so a backward un-compatible change needs to be introduced here.

The new Firewall Alias module has a new home in the XML Tree and the XML generated follows different patterns.

For example:

- it includes versioning of the module that created the XML
- uuids are provided as an Attribute @uuid of the alias element
- multiple values provided for an alias are separated by new line characters.

**Comment by rvalle** [comment]
As discussed in this forum thread: https://forum.opnsense.org/index.php?topic=14289.0

Looks like migration of modules, like Alias, will start taking place.

Perhaps it would be a good idea to create an v2 branch for this purpose, as generated XML will break backwards compatibility.

**Comment by rudibroekhuizen** [comment]
Merged into master. I will release a new version today. Version v1.2 of this repo uses the old aliases notation, used till OPNsense version 18.7.5
